dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: iiLKGTQouDau0vb8GhJ6rzinx5fH188ANCDap6avtm/YxfNVllvNfc9tdHaFsbtuxlDlQuRcmaGS74h0PfoWNIfhz67Jwu4PptrPIYUlGH3rp7620cDLtYQnRmTnbMEPVt+ldIv1/YieMdMvoZBzt733KW6nKo2+jGWjktTshUlOZ+FeIvBSLQU4GG29lsya7QLz1r0i/6o0AuHOTdWhogqwRlH3Da3+Cu4UeBZbslkxvY1oqa+BSaaxGvOpMnjH9WoS0YbBoJRXDP3yKEGar5I5KO1TsqR/YHMOoE7mSp9bIn2wIlQ6NaTjMy9Zs9xjabWLgJEgkT1zkTYsQLaDiSPFIPjGdEzyTdRIkIudvnS2h3qj0a0WnIvsgOg9ow5mmHhelj+xxfx/xPlbD3vyUYUlJPIHfIAAcxjh8dtjwRtpicmYCO0ynJieBxrzQ5vb9nbNdzuTIhSfENQc1Xuprh9JIJlf/xroZ8Hpe9v1VWF8ffo2uAgxy4S5krInH6JIReTaV0g8OzOMq7+jxYj/kjwlMsvCZyQ0/srSfcq2MDd4P4bdcdS5+bE28cbW7Ueci6DDaQ95+hZGfRClf6SQZVjV5tPQTiEPlSY1ijWk45I+ZnB++dL6ofWLm58v9yVT9eMxbQTPrgreFSz6FJfQEXA4UqEIrDDytD9NT0dzCFI=
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.63.1