dist: xenial
sudo: required

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version # prints the Hugo version, just in case.
  - hugo # build the website

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "p1EHf+V7sggWifmMUPmZ3rtItnqDzJwWT8pTwUI6F59X71vCLUquJYN/oLpFjrPegQOvvPVXUtQvd91TSCXkcXrnShG4t+8KmjfPA1Ixhd2cl6JlmJCcCDC3oPYTUJfyQZpbhHtT2jTFlT5AuEtqKbwxKhhrVxnuosOsM52KI2FKP1bYRn2HDtN4KuPhLQbwyHLn7SFVL7cS4BseirSXamim8YZm5EIHLzitqD1rpW60vi8e76kVocYajvLTzngSETRSjTIou+1htw0e7JO+jUwfzXIsuaLiWzdwDm3kr4oxW5PXhbQpgwiYtTx7ioFJJo6PzCKdSqLgpRXBZ9fplY/V5UKLmdEfu/JFFRspzuQEC/4XonFu+e/NCKZe+scm+KV3oISENxcIa2cNPCIeABBvVil4BI3B9RX7LmS7R2L61Up5GkK8exuIWeSnagSZLpOH/dZczmTVPixmSjwNxJI+ZWskn2i/sebNoIc1+iKsdSpuypRltBqnpPDkTushwxvCa2eNqkSbHJYoc5lfFDDc/2nxTwryBQ15f2e3NRl8Agb17mNzSHMYNOXZia6lvbzOL468kJg7PS+CzL8Vm8huTcgiYdmJKvDCKbXO/0BQRTTYBxgUAE+pguwFKVzGRPx4QYGC3JNfSLZQtKyXzIIAi/nAa9xCETacvesz6VQ="
  on:
    branch: master

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.63.1